# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.21.0"

gem "artii", "~> 2.1"

gem "bar-of-progress", "~> 0.1.3"
